import { readFileSync } from "fs";

import { regpCPU } from "./emulator/regpCPU.js";
import { ASM } from "./assembly/assembler.js";
import { DSM } from "./assembly/disassembler.js";

const disassembleCode = () => {
    const fileName   = process.argv[3];
    const byteCodes  = readFileSync(fileName, "utf-8");

    DSM.load(JSON.parse(byteCodes));

    const asmCode = DSM.run();
    console.log(asmCode);
}

const runCode = () => {
    const fileName = process.argv[3];
    const isDebug  = process.argv[4] === "debug";
    
    const program  = readFileSync(fileName, "utf-8");
    const bytes    = ASM.assemble(program);

    if (isDebug) {
        console.log("Generated bytecode: ", JSON.stringify(bytes));
        console.log("");
    }

    regpCPU.load(bytes);

    if (isDebug) {
        console.log("Running program...");
        console.log("");
    }

    regpCPU.run();
}

try {
    const mode = process.argv[2];
    if (mode === "asm") {
        runCode();
    } else if (mode === "dsm") {
        disassembleCode();
    }
} catch (error) {
    console.error("An error has accoured: ", error);
}