import { regpCPU } from "./emulator/regpCPU.js";
import { ASM } from "./assembly/assembler.js";
import { readFileSync } from "fs";

try {
    const fileName = process.argv[2];
    const isDebug  = process.argv[3] === "debug";
    const program  = readFileSync(fileName, "utf-8");
    const bytes    = ASM.assemble(program);

    if (isDebug) {
        console.log("Generated bytecode: ", bytes);
        console.log("");
    }

    regpCPU.load(bytes);

    if (isDebug) {
        console.log("Running program...");
        console.log("");
    }

    regpCPU.run();
} catch (error) {
    console.error("An error has accoured: ", error);
}